### ISSUE TITLE
CCAN Integration

### ISSUE THREAD

**Issue by rmg** [clibs/clib#69]
There are a decent number of little portable C libraries already available via CCAN. Perhaps someone can import those libraries, or come up with a way of indexing them? It would be a shame to ignore the work that has been done over the past several years: http://ccodearchive.net/list.html

**Comment by jb55** [comment]
Was this fixed in #128 ?

**Comment by stephenmathieson** [comment]
Not quite fixed yet; we need to automate creating repos for the ccan packages.
